*** Starting uWSGI 2.0.23 (64bit) on [Tue Feb  6 08:18:02 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55d2c9d8d0a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55d2c9d8d0a0 pid: 3352 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3352)
spawned uWSGI worker 1 (pid: 3353, cores: 1)
Tue Feb  6 17:48:14 2024 - received message 0 from emperor
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock removed.
*** Starting uWSGI 2.0.23 (64bit) on [Tue Feb  6 08:57:46 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x558bc715c0a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x558bc715c0a0 pid: 3633 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3633)
spawned uWSGI worker 1 (pid: 3634, cores: 1)
Not Found: /
[pid: 3634|app: 0|req: 1/1] 211.118.99.10 () {44 vars in 795 bytes} [Tue Feb  6 17:58:20 2024] GET / => generated 2226 bytes in 24 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /
[pid: 3634|app: 0|req: 2/2] 211.118.99.10 () {40 vars in 733 bytes} [Tue Feb  6 17:58:21 2024] GET / => generated 2226 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
Tue Feb  6 18:00:47 2024 - received message 0 from emperor
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock removed.
*** Starting uWSGI 2.0.23 (64bit) on [Tue Feb 13 07:58:10 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5566f4a520a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x5566f4a520a0 pid: 410 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 410)
spawned uWSGI worker 1 (pid: 624, cores: 1)
Tue Feb 13 17:02:50 2024 - received message 1 from emperor
...gracefully killing workers...
Gracefully killing worker 1 (pid: 624)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /etc/uwsgi/sites
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock)
running /usr/local/bin/uwsgi
*** has_emperor mode detected (fd: 7) ***
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.23 (64bit) on [Tue Feb 13 17:02:51 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x559672190c50
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x559672190c50 pid: 410 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 410)
spawned uWSGI worker 1 (pid: 1362, cores: 1)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /
[pid: 1362|app: 0|req: 1/1] 220.126.59.229 () {40 vars in 733 bytes} [Tue Feb 13 17:07:17 2024] GET / => generated 57624 bytes in 108 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[pid: 1362|app: 0|req: 2/2] 220.126.59.229 () {40 vars in 685 bytes} [Tue Feb 13 17:07:20 2024] GET /favicon.ico => generated 57686 bytes in 28 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /
[pid: 1362|app: 0|req: 3/3] 220.126.59.229 () {44 vars in 812 bytes} [Tue Feb 13 17:07:20 2024] GET / => generated 57925 bytes in 28 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[pid: 1362|app: 0|req: 4/4] 220.126.59.229 () {40 vars in 685 bytes} [Tue Feb 13 17:07:20 2024] GET /favicon.ico => generated 57686 bytes in 28 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /index.do
[pid: 1362|app: 0|req: 5/5] 220.126.59.229 () {40 vars in 749 bytes} [Tue Feb 13 17:07:28 2024] GET /index.do => generated 57808 bytes in 28 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[pid: 1362|app: 0|req: 6/6] 220.126.59.229 () {40 vars in 693 bytes} [Tue Feb 13 17:07:29 2024] GET /favicon.ico => generated 57694 bytes in 27 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /index.do
[pid: 1362|app: 0|req: 7/7] 220.126.59.229 () {44 vars in 828 bytes} [Tue Feb 13 17:07:29 2024] GET /index.do => generated 58109 bytes in 27 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[pid: 1362|app: 0|req: 8/8] 220.126.59.229 () {40 vars in 693 bytes} [Tue Feb 13 17:07:29 2024] GET /favicon.ico => generated 57694 bytes in 27 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /index.do
[pid: 1362|app: 0|req: 9/9] 220.126.59.229 () {42 vars in 780 bytes} [Tue Feb 13 17:09:38 2024] GET /index.do => generated 57945 bytes in 30 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[pid: 1362|app: 0|req: 10/10] 220.126.59.229 () {40 vars in 693 bytes} [Tue Feb 13 17:09:38 2024] GET /favicon.ico => generated 57694 bytes in 28 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /index.do
[pid: 1362|app: 0|req: 11/11] 220.126.59.229 () {44 vars in 828 bytes} [Tue Feb 13 17:09:38 2024] GET /index.do => generated 58109 bytes in 29 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '3.35.235.165'. You may need to add '3.35.235.165' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[pid: 1362|app: 0|req: 12/12] 220.126.59.229 () {40 vars in 693 bytes} [Tue Feb 13 17:09:38 2024] GET /favicon.ico => generated 57694 bytes in 28 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
Tue Feb 13 17:10:22 2024 - received message 0 from emperor
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM WARNING: unix socket /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock changed inode. Skip removal
*** Starting uWSGI 2.0.23 (64bit) on [Tue Feb 13 08:10:25 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x556d2c0410a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x556d2c0410a0 pid: 1397 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1397)
spawned uWSGI worker 1 (pid: 1398, cores: 1)
[pid: 1398|app: 0|req: 1/1] 220.126.59.229 () {42 vars in 780 bytes} [Tue Feb 13 17:11:02 2024] GET /index.do => generated 210 bytes in 204 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /favicon.ico
[pid: 1398|app: 0|req: 2/2] 220.126.59.229 () {40 vars in 693 bytes} [Tue Feb 13 17:11:02 2024] GET /favicon.ico => generated 2276 bytes in 8 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 1398|app: 0|req: 3/3] 220.126.59.229 () {44 vars in 828 bytes} [Tue Feb 13 17:11:02 2024] GET /index.do => generated 210 bytes in 16 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 1398|app: 0|req: 4/4] 221.154.186.27 () {42 vars in 780 bytes} [Tue Feb 13 17:13:36 2024] GET /index.do => generated 210 bytes in 18 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 1398|app: 0|req: 5/5] 221.154.186.27 () {44 vars in 828 bytes} [Tue Feb 13 17:13:37 2024] GET /index.do => generated 210 bytes in 18 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 1398|app: 0|req: 6/6] 221.154.186.27 () {42 vars in 780 bytes} [Tue Feb 13 17:23:13 2024] GET /index.do => generated 210 bytes in 16 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 1398|app: 0|req: 7/7] 221.154.186.27 () {44 vars in 828 bytes} [Tue Feb 13 17:23:13 2024] GET /index.do => generated 210 bytes in 15 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
Not Found: /.env
[pid: 1398|app: 0|req: 8/8] 185.254.196.173 () {36 vars in 504 bytes} [Tue Feb 13 18:09:41 2024] GET /.env => generated 2255 bytes in 72 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 1398|app: 0|req: 9/9] 185.254.196.173 () {40 vars in 611 bytes} [Tue Feb 13 18:09:42 2024] POST / => generated 2226 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /Core/Skin/Login.aspx
[pid: 1398|app: 0|req: 10/10] 150.109.159.4 () {42 vars in 773 bytes} [Tue Feb 13 18:26:52 2024] HEAD /Core/Skin/Login.aspx => generated 2307 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.23 (64bit) on [Wed Feb 14 08:20:42 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55938c4700a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x55938c4700a0 pid: 395 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 395)
spawned uWSGI worker 1 (pid: 618, cores: 1)
SIGINT/SIGTERM received...killing workers...
Wed Feb 14 17:24:26 2024 - received message 0 from emperor
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock removed.
*** Starting uWSGI 2.0.23 (64bit) on [Wed Feb 14 08:24:29 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x562c258590a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x562c258590a0 pid: 909 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 909)
spawned uWSGI worker 1 (pid: 910, cores: 1)
[pid: 910|app: 0|req: 1/1] 220.126.59.229 () {40 vars in 750 bytes} [Wed Feb 14 17:25:14 2024] GET /index.do => generated 210 bytes in 106 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Not Found: /favicon.ico
[pid: 910|app: 0|req: 2/2] 220.126.59.229 () {40 vars in 695 bytes} [Wed Feb 14 17:25:15 2024] GET /favicon.ico => generated 2277 bytes in 13 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 3/3] 220.126.59.229 () {44 vars in 829 bytes} [Wed Feb 14 17:25:17 2024] GET /index.do => generated 210 bytes in 16 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
Not Found: /
[pid: 910|app: 0|req: 4/4] 192.241.195.115 () {34 vars in 375 bytes} [Wed Feb 14 17:28:55 2024] GET / => generated 2226 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 910|app: 0|req: 5/5] 139.162.84.205 () {30 vars in 400 bytes} [Wed Feb 14 17:41:51 2024] GET / => generated 56660 bytes in 54 msecs (HTTP/1.0 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'www.madblog.co.kr'. You may need to add 'www.madblog.co.kr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.madblog.co.kr'. You may need to add 'www.madblog.co.kr' to ALLOWED_HOSTS.
Bad Request: /
[pid: 910|app: 0|req: 6/6] 220.126.59.229 () {40 vars in 738 bytes} [Wed Feb 14 17:50:27 2024] GET / => generated 57699 bytes in 28 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'www.madblog.co.kr'. You may need to add 'www.madblog.co.kr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.madblog.co.kr'. You may need to add 'www.madblog.co.kr' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[pid: 910|app: 0|req: 7/7] 220.126.59.229 () {40 vars in 695 bytes} [Wed Feb 14 17:50:28 2024] GET /favicon.ico => generated 57766 bytes in 28 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'www.madblog.co.kr'. You may need to add 'www.madblog.co.kr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.madblog.co.kr'. You may need to add 'www.madblog.co.kr' to ALLOWED_HOSTS.
Bad Request: /
[pid: 910|app: 0|req: 8/8] 220.126.59.229 () {44 vars in 817 bytes} [Wed Feb 14 17:50:28 2024] GET / => generated 58000 bytes in 27 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'www.madblog.co.kr'. You may need to add 'www.madblog.co.kr' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.madblog.co.kr'. You may need to add 'www.madblog.co.kr' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[pid: 910|app: 0|req: 9/9] 220.126.59.229 () {40 vars in 695 bytes} [Wed Feb 14 17:50:28 2024] GET /favicon.ico => generated 57766 bytes in 28 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 10/10] 220.126.59.229 () {40 vars in 750 bytes} [Wed Feb 14 17:57:30 2024] GET /index.do => generated 210 bytes in 16 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 11/11] 220.126.59.229 () {44 vars in 829 bytes} [Wed Feb 14 17:57:30 2024] GET /index.do => generated 210 bytes in 16 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 12/12] 220.126.59.229 () {40 vars in 750 bytes} [Wed Feb 14 18:05:57 2024] GET /index.do => generated 210 bytes in 16 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 13/13] 220.126.59.229 () {44 vars in 829 bytes} [Wed Feb 14 18:05:57 2024] GET /index.do => generated 210 bytes in 17 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 14/14] 220.126.59.229 () {42 vars in 793 bytes} [Wed Feb 14 18:06:47 2024] GET /index.do => generated 210 bytes in 16 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 15/15] 220.126.59.229 () {44 vars in 841 bytes} [Wed Feb 14 18:06:47 2024] GET /index.do => generated 210 bytes in 16 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
Not Found: /
[pid: 910|app: 0|req: 16/16] 64.62.197.117 () {34 vars in 493 bytes} [Wed Feb 14 18:21:34 2024] GET / => generated 2226 bytes in 7 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'ec2-13-209-82-108.ap-northeast-2.compute.amazonaws.com'. You may need to add 'ec2-13-209-82-108.ap-northeast-2.compute.amazonaws.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/pyblog/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'ec2-13-209-82-108.ap-northeast-2.compute.amazonaws.com'. You may need to add 'ec2-13-209-82-108.ap-northeast-2.compute.amazonaws.com' to ALLOWED_HOSTS.
Bad Request: /
[pid: 910|app: 0|req: 17/17] 54.70.53.60 () {42 vars in 740 bytes} [Wed Feb 14 18:45:40 2024] GET / => generated 58315 bytes in 27 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Not Found: /
[pid: 910|app: 0|req: 18/18] 113.53.155.3 () {32 vars in 454 bytes} [Wed Feb 14 18:48:21 2024] GET / => generated 2229 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 910|app: 0|req: 19/19] 220.126.59.229 () {40 vars in 746 bytes} [Wed Feb 14 19:04:07 2024] GET / => generated 2226 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 910|app: 0|req: 20/20] 220.126.59.229 () {44 vars in 825 bytes} [Wed Feb 14 19:04:07 2024] GET / => generated 2226 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 910|app: 0|req: 21/21] 220.126.59.229 () {42 vars in 777 bytes} [Wed Feb 14 19:05:05 2024] GET / => generated 2226 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 22/22] 220.126.59.229 () {40 vars in 762 bytes} [Wed Feb 14 19:06:05 2024] GET /index.do => generated 210 bytes in 21 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 23/23] 220.126.59.229 () {44 vars in 841 bytes} [Wed Feb 14 19:06:05 2024] GET /index.do => generated 210 bytes in 16 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
Not Found: /
[pid: 910|app: 0|req: 24/24] 220.126.59.229 () {40 vars in 746 bytes} [Wed Feb 14 19:06:15 2024] GET / => generated 2226 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 910|app: 0|req: 25/25] 220.126.59.229 () {44 vars in 825 bytes} [Wed Feb 14 19:06:15 2024] GET / => generated 2226 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 26/26] 220.126.59.229 () {44 vars in 824 bytes} [Wed Feb 14 19:15:26 2024] GET /index.do => generated 210 bytes in 54 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 910|app: 0|req: 27/27] 220.126.59.229 () {44 vars in 841 bytes} [Wed Feb 14 19:15:27 2024] GET /index.do => generated 210 bytes in 16 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
Not Found: /
[pid: 910|app: 0|req: 28/28] 220.126.59.229 () {40 vars in 746 bytes} [Wed Feb 14 19:15:35 2024] GET / => generated 2226 bytes in 7 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /
[pid: 910|app: 0|req: 29/29] 220.126.59.229 () {44 vars in 825 bytes} [Wed Feb 14 19:15:35 2024] GET / => generated 2226 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
Wed Feb 14 19:16:49 2024 - received message 0 from emperor
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock removed.
*** Starting uWSGI 2.0.23 (64bit) on [Wed Feb 14 10:16:52 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55b41f4530a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55b41f4530a0 pid: 1405 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1405)
spawned uWSGI worker 1 (pid: 1406, cores: 1)
[pid: 1406|app: 0|req: 1/1] 220.126.59.229 () {44 vars in 824 bytes} [Wed Feb 14 19:16:57 2024] GET /index.do => generated 210 bytes in 171 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 1406|app: 0|req: 2/2] 220.126.59.229 () {40 vars in 746 bytes} [Wed Feb 14 19:17:04 2024] GET / => generated 41913 bytes in 2 msecs (HTTP/1.1 200) 6 headers in 209 bytes (1 switches on core 0)
[pid: 1406|app: 0|req: 3/3] 220.126.59.229 () {44 vars in 825 bytes} [Wed Feb 14 19:17:04 2024] GET / => generated 41913 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 209 bytes (1 switches on core 0)
Not Found: /js/scripts.js
[pid: 1406|app: 0|req: 4/4] 220.126.59.229 () {40 vars in 642 bytes} [Wed Feb 14 19:17:04 2024] GET /js/scripts.js => generated 2560 bytes in 11 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /assets/demo/chart-area-demo.js
[pid: 1406|app: 0|req: 5/5] 220.126.59.229 () {40 vars in 676 bytes} [Wed Feb 14 19:17:04 2024] GET /assets/demo/chart-area-demo.js => generated 2611 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /assets/demo/chart-bar-demo.js
[pid: 1406|app: 0|req: 6/6] 220.126.59.229 () {40 vars in 674 bytes} [Wed Feb 14 19:17:04 2024] GET /assets/demo/chart-bar-demo.js => generated 2608 bytes in 4 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /js/datatables-simple-demo.js
[pid: 1406|app: 0|req: 7/7] 220.126.59.229 () {40 vars in 672 bytes} [Wed Feb 14 19:17:04 2024] GET /js/datatables-simple-demo.js => generated 2605 bytes in 4 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 1406|app: 0|req: 8/8] 220.126.59.229 () {42 vars in 777 bytes} [Wed Feb 14 19:19:51 2024] GET / => generated 41913 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 209 bytes (1 switches on core 0)
Not Found: /js/scripts.js
[pid: 1406|app: 0|req: 9/9] 220.126.59.229 () {40 vars in 642 bytes} [Wed Feb 14 19:19:51 2024] GET /js/scripts.js => generated 2560 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /assets/demo/chart-area-demo.js
[pid: 1406|app: 0|req: 10/10] 220.126.59.229 () {40 vars in 676 bytes} [Wed Feb 14 19:19:51 2024] GET /assets/demo/chart-area-demo.js => generated 2611 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /assets/demo/chart-bar-demo.js
[pid: 1406|app: 0|req: 11/11] 220.126.59.229 () {40 vars in 674 bytes} [Wed Feb 14 19:19:51 2024] GET /assets/demo/chart-bar-demo.js => generated 2608 bytes in 4 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /js/datatables-simple-demo.js
[pid: 1406|app: 0|req: 12/12] 220.126.59.229 () {40 vars in 672 bytes} [Wed Feb 14 19:19:52 2024] GET /js/datatables-simple-demo.js => generated 2605 bytes in 4 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
Wed Feb 14 19:21:09 2024 - received message 0 from emperor
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock removed.
*** Starting uWSGI 2.0.23 (64bit) on [Wed Feb 14 10:21:12 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55707eb5e0a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55707eb5e0a0 pid: 1448 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1448)
spawned uWSGI worker 1 (pid: 1449, cores: 1)
[pid: 1449|app: 0|req: 1/1] 220.126.59.229 () {42 vars in 777 bytes} [Wed Feb 14 19:21:32 2024] GET / => generated 41913 bytes in 23 msecs (HTTP/1.1 200) 6 headers in 209 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 1449|app: 0|req: 2/2] 220.126.59.229 () {44 vars in 825 bytes} [Wed Feb 14 19:21:32 2024] GET / => generated 41913 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 209 bytes (1 switches on core 0)
[pid: 1449|app: 0|req: 3/3] 220.126.59.229 () {40 vars in 642 bytes} [Wed Feb 14 19:21:32 2024] GET /js/scripts.js => generated 179 bytes in 7 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1449|app: 0|req: 4/4] 220.126.59.229 () {40 vars in 676 bytes} [Wed Feb 14 19:21:32 2024] GET /assets/demo/chart-area-demo.js => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1449|app: 0|req: 5/5] 220.126.59.229 () {40 vars in 672 bytes} [Wed Feb 14 19:21:32 2024] GET /js/datatables-simple-demo.js => generated 179 bytes in 0 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1449|app: 0|req: 6/6] 220.126.59.229 () {40 vars in 674 bytes} [Wed Feb 14 19:21:32 2024] GET /assets/demo/chart-bar-demo.js => generated 179 bytes in 0 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
Wed Feb 14 19:25:41 2024 - received message 1 from emperor
...gracefully killing workers...
Gracefully killing worker 1 (pid: 1449)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /etc/uwsgi/sites
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock)
running /usr/local/bin/uwsgi
*** has_emperor mode detected (fd: 7) ***
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.23 (64bit) on [Wed Feb 14 19:25:42 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x555b4fd3dc50
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x555b4fd3dc50 pid: 1448 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1448)
spawned uWSGI worker 1 (pid: 1464, cores: 1)
SIGINT/SIGTERM received...killing workers...
Wed Feb 14 19:29:49 2024 - received message 0 from emperor
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM WARNING: unix socket /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock changed inode. Skip removal
*** Starting uWSGI 2.0.23 (64bit) on [Thu Feb 15 07:34:48 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55a158c4e0a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x55a158c4e0a0 pid: 403 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 403)
spawned uWSGI worker 1 (pid: 622, cores: 1)
[pid: 622|app: 0|req: 1/1] 124.90.226.57 () {32 vars in 445 bytes} [Thu Feb 15 17:02:11 2024] GET / => generated 143 bytes in 169 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 622|app: 0|req: 2/2] 139.162.84.205 () {30 vars in 412 bytes} [Thu Feb 15 17:39:53 2024] GET / => generated 143 bytes in 31 msecs (HTTP/1.0 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 622|app: 0|req: 3/3] 150.109.159.4 () {42 vars in 787 bytes} [Thu Feb 15 18:05:49 2024] HEAD /Core/Skin/Login.aspx => generated 143 bytes in 12 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 622|app: 0|req: 4/4] 71.6.199.23 () {34 vars in 527 bytes} [Thu Feb 15 18:20:23 2024] GET / => generated 143 bytes in 12 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 622|app: 0|req: 5/5] 71.6.199.23 () {30 vars in 350 bytes} [Thu Feb 15 18:20:23 2024] GET /robots.txt => generated 143 bytes in 12 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 622|app: 0|req: 6/6] 71.6.199.23 () {30 vars in 352 bytes} [Thu Feb 15 18:20:24 2024] GET /sitemap.xml => generated 143 bytes in 11 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 622|app: 0|req: 7/7] 71.6.199.23 () {30 vars in 378 bytes} [Thu Feb 15 18:20:24 2024] GET /.well-known/security.txt => generated 143 bytes in 11 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 622|app: 0|req: 8/8] 71.6.199.23 () {36 vars in 538 bytes} [Thu Feb 15 18:20:24 2024] GET /favicon.ico => generated 143 bytes in 12 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 622|app: 0|req: 9/9] 159.203.192.38 () {34 vars in 387 bytes} [Thu Feb 15 18:45:56 2024] GET / => generated 143 bytes in 12 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
Thu Feb 15 19:08:14 2024 - received message 0 from emperor
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock removed.
*** Starting uWSGI 2.0.23 (64bit) on [Thu Feb 15 10:08:17 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x56467f15c0a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x56467f15c0a0 pid: 1524 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1524)
spawned uWSGI worker 1 (pid: 1525, cores: 1)
[pid: 1525|app: 0|req: 1/1] 220.126.59.229 () {40 vars in 747 bytes} [Thu Feb 15 19:08:30 2024] GET / => generated 8933 bytes in 34 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 1525|app: 0|req: 2/2] 220.126.59.229 () {40 vars in 701 bytes} [Thu Feb 15 19:08:30 2024] GET /favicon.ico => generated 179 bytes in 3 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 3/3] 220.126.59.229 () {42 vars in 790 bytes} [Thu Feb 15 19:09:52 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 4/4] 220.126.59.229 () {40 vars in 763 bytes} [Thu Feb 15 19:09:58 2024] GET /index.do => generated 210 bytes in 56 msecs (HTTP/1.1 200) 6 headers in 207 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 5/5] 220.126.59.229 () {40 vars in 759 bytes} [Thu Feb 15 19:10:09 2024] GET /admin/ => generated 0 bytes in 35 msecs (HTTP/1.1 302) 10 headers in 372 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 6/6] 220.126.59.229 () {40 vars in 796 bytes} [Thu Feb 15 19:10:09 2024] GET /admin/login/?next=/admin/ => generated 2238 bytes in 40 msecs (HTTP/1.1 200) 10 headers in 470 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 7/7] 220.126.59.229 () {52 vars in 1100 bytes} [Thu Feb 15 19:10:17 2024] POST /admin/login/?next=/admin/ => generated 0 bytes in 347 msecs (HTTP/1.1 302) 12 headers in 634 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 8/8] 220.126.59.229 () {46 vars in 954 bytes} [Thu Feb 15 19:10:17 2024] GET /admin/ => generated 6110 bytes in 38 msecs (HTTP/1.1 200) 10 headers in 470 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 9/9] 220.126.59.229 () {44 vars in 928 bytes} [Thu Feb 15 19:10:21 2024] GET /admin/blog/pyblog/ => generated 7592 bytes in 100 msecs (HTTP/1.1 200) 10 headers in 470 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 10/10] 220.126.59.229 () {42 vars in 763 bytes} [Thu Feb 15 19:10:21 2024] GET /admin/jsi18n/ => generated 8911 bytes in 23 msecs (HTTP/1.1 200) 7 headers in 230 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 11/11] 220.126.59.229 () {44 vars in 948 bytes} [Thu Feb 15 19:10:23 2024] GET /admin/blog/pyblog/add/ => generated 19293 bytes in 73 msecs (HTTP/1.1 200) 10 headers in 471 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 12/12] 220.126.59.229 () {42 vars in 767 bytes} [Thu Feb 15 19:10:23 2024] GET /admin/jsi18n/ => generated 8911 bytes in 19 msecs (HTTP/1.1 200) 7 headers in 230 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 13/13] 220.126.59.229 () {44 vars in 928 bytes} [Thu Feb 15 19:10:26 2024] GET /admin/blog/pyblog/ => generated 7592 bytes in 73 msecs (HTTP/1.1 200) 10 headers in 470 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 14/14] 220.126.59.229 () {44 vars in 891 bytes} [Thu Feb 15 19:10:32 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 15/15] 220.126.59.229 () {46 vars in 922 bytes} [Thu Feb 15 19:12:07 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 16/16] 220.126.59.229 () {46 vars in 922 bytes} [Thu Feb 15 19:16:42 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 17/17] 150.109.159.4 () {42 vars in 787 bytes} [Thu Feb 15 19:23:46 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 18/18] 117.235.27.65 () {32 vars in 457 bytes} [Thu Feb 15 20:08:31 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 19/19] 150.109.159.4 () {42 vars in 787 bytes} [Thu Feb 15 20:43:10 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 20/20] 45.56.108.128 () {30 vars in 469 bytes} [Thu Feb 15 20:49:47 2024] GET /systembc/password.php => generated 143 bytes in 16 msecs (HTTP/1.0 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 21/21] 218.250.161.124 () {30 vars in 431 bytes} [Thu Feb 15 21:09:44 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 22/22] 35.203.211.128 () {30 vars in 592 bytes} [Thu Feb 15 21:17:50 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 23/23] 139.162.84.205 () {30 vars in 412 bytes} [Thu Feb 15 21:37:52 2024] GET / => generated 143 bytes in 14 msecs (HTTP/1.0 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 24/24] 185.224.128.55 () {44 vars in 774 bytes} [Thu Feb 15 21:55:21 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 25/25] 150.109.159.4 () {42 vars in 787 bytes} [Thu Feb 15 22:03:05 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 26/26] 91.92.244.120 () {44 vars in 773 bytes} [Thu Feb 15 22:11:00 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 27/27] 150.109.159.4 () {42 vars in 787 bytes} [Thu Feb 15 23:24:22 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 28/28] 185.180.143.8 () {34 vars in 480 bytes} [Fri Feb 16 00:02:54 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 29/29] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 00:44:50 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 30/30] 130.211.54.158 () {42 vars in 557 bytes} [Fri Feb 16 00:57:28 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 31/31] 139.162.84.205 () {30 vars in 412 bytes} [Fri Feb 16 01:37:42 2024] GET / => generated 143 bytes in 12 msecs (HTTP/1.0 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 32/32] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 02:05:22 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 33/33] 103.154.49.97 () {32 vars in 457 bytes} [Fri Feb 16 02:47:44 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 34/34] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 03:25:27 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 35/35] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 04:44:52 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 36/36] 138.199.31.17 () {30 vars in 429 bytes} [Fri Feb 16 04:49:29 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 37/37] 139.162.84.205 () {30 vars in 412 bytes} [Fri Feb 16 05:44:10 2024] GET / => generated 143 bytes in 12 msecs (HTTP/1.0 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 38/38] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 06:04:04 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 39/39] 198.235.24.150 () {30 vars in 580 bytes} [Fri Feb 16 06:26:44 2024] GET / => generated 143 bytes in 12 msecs (HTTP/1.0 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 40/40] 45.164.35.1 () {32 vars in 455 bytes} [Fri Feb 16 07:12:53 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 41/41] 141.98.7.206 () {30 vars in 347 bytes} [Fri Feb 16 07:18:30 2024] GET /nginx_status => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 42/42] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 07:23:14 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 43/43] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 08:42:09 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 44/44] 192.241.159.156 () {34 vars in 478 bytes} [Fri Feb 16 09:16:36 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 45/45] 192.241.159.156 () {34 vars in 395 bytes} [Fri Feb 16 09:16:37 2024] GET /form.html => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 46/46] 192.241.159.156 () {34 vars in 392 bytes} [Fri Feb 16 09:16:37 2024] GET /upl.php => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 47/47] 192.241.159.156 () {34 vars in 490 bytes} [Fri Feb 16 09:16:38 2024] GET /geoip/ => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 48/48] 192.241.159.156 () {34 vars in 500 bytes} [Fri Feb 16 09:16:38 2024] GET /favicon.ico => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 49/49] 192.241.159.156 () {34 vars in 488 bytes} [Fri Feb 16 09:16:39 2024] GET /1.php => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 50/50] 192.241.159.156 () {34 vars in 496 bytes} [Fri Feb 16 09:16:39 2024] GET /bundle.js => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 51/51] 192.241.159.156 () {34 vars in 490 bytes} [Fri Feb 16 09:16:39 2024] GET /files/ => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 52/52] 192.241.159.156 () {34 vars in 520 bytes} [Fri Feb 16 09:16:40 2024] GET /systembc/password.php => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 53/53] 192.241.159.156 () {34 vars in 502 bytes} [Fri Feb 16 09:16:40 2024] GET /password.php => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 54/54] 192.241.159.156 () {34 vars in 494 bytes} [Fri Feb 16 09:16:41 2024] GET /info.php => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 55/55] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 10:01:59 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 56/56] 163.123.142.146 () {36 vars in 584 bytes} [Fri Feb 16 11:04:13 2024] GET /.env => generated 179 bytes in 72 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 57/57] 163.123.142.146 () {40 vars in 691 bytes} [Fri Feb 16 11:04:13 2024] POST / => generated 1529 bytes in 12 msecs (HTTP/1.1 403) 6 headers in 215 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 58/58] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 11:20:05 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 59/59] 159.203.192.45 () {34 vars in 415 bytes} [Fri Feb 16 11:28:44 2024] GET /portal/redlion => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 60/60] 205.210.31.60 () {30 vars in 591 bytes} [Fri Feb 16 12:03:06 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 61/61] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 12:37:57 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 62/62] 198.235.24.146 () {30 vars in 592 bytes} [Fri Feb 16 13:22:22 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 63/63] 139.162.84.205 () {30 vars in 412 bytes} [Fri Feb 16 13:38:00 2024] GET / => generated 143 bytes in 26 msecs (HTTP/1.0 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 64/64] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 13:55:57 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 65/65] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 15:14:44 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 66/66] 35.203.210.225 () {30 vars in 592 bytes} [Fri Feb 16 15:38:15 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 67/67] 198.235.24.82 () {30 vars in 579 bytes} [Fri Feb 16 15:56:54 2024] GET / => generated 143 bytes in 90 msecs (HTTP/1.0 400) 4 headers in 172 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 68/68] 35.195.93.98 () {42 vars in 553 bytes} [Fri Feb 16 15:57:32 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 69/69] 185.242.226.10 () {34 vars in 481 bytes} [Fri Feb 16 16:20:54 2024] GET / => generated 8933 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 70/70] 150.109.159.4 () {42 vars in 787 bytes} [Fri Feb 16 16:33:59 2024] HEAD /Core/Skin/Login.aspx => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
[pid: 1525|app: 0|req: 71/71] 159.203.208.30 () {34 vars in 399 bytes} [Fri Feb 16 16:53:13 2024] GET /hudson => generated 179 bytes in 1 msecs (HTTP/1.1 404) 6 headers in 214 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
Fri Feb 16 17:35:40 2024 - received message 0 from emperor
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock removed.
*** Starting uWSGI 2.0.23 (64bit) on [Fri Feb 16 08:37:46 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x557efe6170a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x557efe6170a0 pid: 390 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 390)
spawned uWSGI worker 1 (pid: 604, cores: 1)
[pid: 604|app: 0|req: 1/1] 139.162.84.205 () {30 vars in 412 bytes} [Fri Feb 16 17:42:27 2024] GET / => generated 143 bytes in 105 msecs (HTTP/1.0 400) 4 headers in 172 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
SIGINT/SIGTERM received...killing workers...
Fri Feb 16 17:47:29 2024 - received message 0 from emperor
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock removed.
*** Starting uWSGI 2.0.23 (64bit) on [Sat Feb 17 06:16:49 2024] ***
compiled with version: 11.4.0 on 29 January 2024 08:02:47
os: Linux-6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
nodename: ip-172-31-2-169
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /etc/uwsgi/sites
writing pidfile to /tmp/project-master.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/ubuntu/PYTHONBLOG/Pyblog
your processes number limit is 3738
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ubuntu/PYTHONBLOG/Pyblog/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
PEP 405 virtualenv detected: /home/ubuntu/pyblog
Set PythonHome to /home/ubuntu/pyblog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5595be6440a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5595be6440a0 pid: 404 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 404)
spawned uWSGI worker 1 (pid: 623, cores: 1)
[pid: 623|app: 0|req: 1/1] 162.243.143.11 () {34 vars in 418 bytes} [Sat Feb 17 15:37:08 2024] GET /manager/text/list => generated 143 bytes in 117 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
